package Xlib.Masks is
    NoEventMask : constant := 0;
    KeyPressMask : constant := (2**0);
    KeyReleaseMask : constant := (2**1);
    ButtonPressMask : constant := (2**2);
    ButtonReleaseMask : constant := (2**3);
    EnterWindowMask : constant := (2**4);
    LeaveWindowMask : constant := (2**5);
    PointerMotionMask : constant := (2**6);
    PointerMotionHintMask : constant := (2**7);
    Button1MotionMask : constant := (2**8);
    Button2MotionMask : constant := (2**9);
    Button3MotionMask : constant := (2**10);
    Button4MotionMask : constant := (2**11);
    Button5MotionMask : constant := (2**12);
    ButtonMotionMask : constant := (2**13);
    KeymapStateMask : constant := (2**14);
    ExposureMask : constant := (2**15);
    VisibilityChangeMask : constant := (2**16);
    StructureNotifyMask : constant := (2**17);
    ResizeRedirectMask : constant := (2**18);
    SubstructureNotifyMask : constant := (2**19);
    SubstructureRedirectMask : constant := (2**20);
    FocusChangeMask : constant := (2**21);
    PropertyChangeMask : constant := (2**22);
    ColormapChangeMask : constant := (2**23);
    OwnerGrabButtonMask : constant := (2**24);
end Xlib.Masks;
